#compose
services:
  biomedCLIPCAP:
    build: .
    image: biomedclipcap
    container_name: biomedCLIPCAP
    working_dir: /workspace
    volumes:
      - ./:/workspace
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    stdin_open: true
    tty: true
